[build]
  command = """
    git clone https://github.com/flutter/flutter.git && \
    cd flutter && \
    git checkout stable && \
    export PATH="$PWD/bin:$PATH" && \
    cd .. && \
    flutter doctor && \
    flutter config --enable-web && \
    flutter build web --release
  """
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"